### ISSUE TITLE
ember-resources: useTask instead of useFunction

### ISSUE THREAD

**Issue by derrabauke** [projectcaluma/ember-emeis#342]
Hey guys @anehx @velrest
Could you help me with the correct usage of `ember-resources` here? Actually I want to perform a task at this point via `useTask`, but I could not get it working and ended up in an infinite loop while I wanted to call `fetchData` and show the *loading state* of the task. That's why we now use `useFunction` instead, like shown below. This works as expected.

JS:
https://github.com/projectcaluma/ember-emeis/blob/5e46febafb795f99814cc5ff5d8b5b5a42365a2f/addon/components/data-table.js#L18-L26

Template:
https://github.com/projectcaluma/ember-emeis/blob/5e46febafb795f99814cc5ff5d8b5b5a42365a2f/addon/components/data-table.hbs#L49-L54

---

**How would you implement it with `useTask`?** They main difficulty here being the display of the *loading state*. 
This version is yielding an error, since you are not allowed to access this task while an instance of it is running.
```js
get isLoading() {
  return this.fetchData.isRunning;
}
```

Would you do something like: 
```js
// data-table.js
...
data = useTask (this, this.fetchData, () => [
    this.args.filter,
    this.search,
    this.sort,
    this.page,
  ]);
...
get isLoading() {
  return this.data.isRunning;
}
```
```hbs
{{!-- data-table.hbs --}}
{{#if this.isLoading}}
    {{!-- loading spinner --}}
  {{else}}
    {{yield
      (hash
        body=(component "data-table/body" models=this.data.value)
        head=(component "data-table/head" sortedBy=this.sort update=this.updateSort)
        refresh=(perform this.fetchData)
      )
    }}
```
*Spoiler alert* this is ending in an infinite loop between the *getter* and `fetchData`

**Comment by anehx** [comment]
```hbs
{{#if this.data.isRunning}}
```
`useTask` exposes the last task instance which has an `isRunning` property

**Comment by derrabauke** [comment]
> ```
> {{#if this.data.isRunning}}
> ```
> 
> `useTask` exposes the last task instance which has an `isRunning` property

Have already tried that and now once more. Still the same result just without the getter. I guess it might be an issue with the usage of the `data-table` component itself. It *yields* alot of components which might wrack some property tracking...
